#pragma once

#define WORLD_WIDTH 384
#define WORLD_HEIGHT 288
#define WORLD_SCALE 3

#define PICKER_PADDING 8
#define PICKER_WIDTH 80
#define PICKER_HEIGHT 24
#define PICKER_SELECTED_COLOR (SDL_Color{0, 0, 255, 64})

#define AUTHOR_HEIGHT 48

#define CELL_TYPES_DIR "assets/cell_types/"

// ---- //

#define PICKER_FULL_WIDTH (PICKER_WIDTH + PICKER_PADDING * 2)
#define PICKER_FULL_HEIGHT (PICKER_HEIGHT + PICKER_PADDING * 2)

#define WORLD_VIEW_WIDTH (WORLD_WIDTH * WORLD_SCALE)
#define WORLD_VIEW_HEIGHT (WORLD_HEIGHT * WORLD_SCALE)

#define WINDOW_MIN_WIDTH (WORLD_VIEW_WIDTH + PICKER_FULL_WIDTH)
#define WINDOW_MIN_HEIGHT (WORLD_VIEW_HEIGHT + AUTHOR_HEIGHT)